sudo: required
services:
  - docker

before_install:
  - docker build -t mattdunson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mattdunson/react-test npm test

after_success:
  - docker build -t mattdunson/multi-client ./client
  - docker build -t mattdunson/multi-nginx ./nginx
  - docker build -t mattdunson/multi-server ./server
  - docker build -t mattdunson/multi-worker  ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mattdunson/multi-client
  - docker push mattdunson/multi-nginx
  - docker push mattdunson/multi-server
  - docker push mattdunson/multi-worker